# In production this should probably be busybox, but let's use ubuntu for a
# fair comparison 
#
# Source: https://index.docker.io/u/tutum/ubuntu-saucy/
FROM tutum/ubuntu-saucy

MAINTAINER Juan Rubio, rubioj@us.ibm.com

# Make sure the package repository is up to date
#RUN echo "deb http://archive.ubuntu.com/ubuntu saucy main universe" > /etc/apt/sources.list
#RUN apt-get update

#RUN apt-get install -y openssh-server

# Change root password
#RUN echo 'root:screencast' |chpasswd
